<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('movies')->insert([
            [
                'id' => 1,
                'title' => 'トリック劇場版',
                'tmdb_id' => 326369,
                'original_title' => 'トリック 劇場版',
                'overview' => 'ある日、奈緒子は災いが起こると言い伝えられる村で「神を演じてほしい」と依頼を受ける。しかし村には自称「神」を名乗る3人の男が待っていた…。',
                'release_year' => 2002,
                'director' => '堤幸彦',
                'country_id' => 1,
                'image1' => '/tt84MQlU6RCMI00jOxIx8jxQfes.jpg',
                'image2' => '',
                'created_at' => '2024-07-17 21:09:01',
                'updated_at' => '2024-07-17 21:09:01',
            ],
            [
                'id' => 2,
                'title' => 'マッドマックス：フュリオサ',
                'tmdb_id' => 786892,
                'original_title' => 'Furiosa: A Mad Max Saga',
                'overview' => '世界崩壊から45年。バイカー軍団に連れ去られ、すべてを奪われた若きフュリオサは故郷への帰還を誓い、MADな世界（マッドワールド）に対峙する——巨大なバイカー軍団、その頂点ディメンタス将軍は可愛い熊の人形を引っさげ改造バイクで絶叫し、さらには、白塗りの兵隊ウォーボーイズたちが神と崇めるイモータン・ジョーは鉄壁の要塞を牛耳り、互いが覇権を争っていた。生き残れるのは狂った奴だけ。怒りの戦士フュリオサよ、復讐のエンジンを鳴らせ！',
                'release_year' => 2024,
                'director' => 'ジョージ・ミラー',
                'country_id' => 2,
                'image1' => '/raph7qjAGTMXaIjVxt6ZDSXRzUr.jpg',
                'image2' => '/uk3xNoCirHkbcfUbgH5UISI23De.jpg',
                'created_at' => '2024-07-17 21:09:01',
                'updated_at' => '2024-07-17 21:09:01',
            ],
            [
                'id' => 3,
                'title' => 'シンドラーのリスト',
                'tmdb_id' => 424,
                'original_title' => "Schindler's List",
                'overview' => '1939年、ポーランド南部の都市クラクフにドイツ軍が侵攻した。ドイツ人実業家のオスカー・シンドラーは、一旗揚げようとこの街にやって来た。彼は 金にものを言わせて巧みに軍の幹部たちに取り入り、ユダヤ人の所有していた工場を払い下げてもらう。ユダヤ人会計士のイツァーク・シュテルンをパートナーに選んだシンドラーは、軍用ホーロー容器の事業を始める。41年3月、ユダヤ人たちは壁に囲まれたゲットー（居住区）に住むことを義務づけられる。シュテルンの活躍で、ゲットーのユ ダヤ人たちが無償の労働力として、シンドラーの工場に続々と集められ事業はたちまち軌道に乗る。',
                'release_year' => 1994,
                'director' => 'スティーブン・スピルバーグ',
                'country_id' => 2,
                'image1' => '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
                'image2' => '/ei5xjikx59WR2oDFl2lNLbtQHkx.jpg',
                'created_at' => '2024-07-17 21:09:01',
                'updated_at' => '2024-07-17 21:09:01',
            ],
            [
                'id' => 4,
                'title' => 'ハリー・ポッターと賢者の石',
                'tmdb_id' => 671,
                'original_title' => "Harry Potter and the Philosopher's Stone",
                'overview' => '両親の死後、親戚の家に預けられたハリー・ポッター少年。そこでは階段下の物置部屋をあてがわれ、何かとこき使われる毎日。そんなある日、ハリー の11歳の誕生日に一通の手紙が届いた。中身はなんと、魔法魔術学校の入学許可証だった。実は、ハリーの両親は優秀な魔法使いだったのだ。手紙に導かれるままホグワーツ魔法魔術学校にたどり着いたハリーは、さっそく魔法使いになるための勉強を始める。ロンとハーマイオニーという友達もでき、楽しい毎日を送るハリーだったが、やがて学校に隠された驚くべき秘密に気づくのだった……。',
                'release_year' => 2001,
                'director' => 'クリス・コロンバス',
                'country_id' => 2,
                'image1' => '/pXvDfEB5kA4cZJ2S2zTXg8cKTsK.jpg',
                'image2' => '/dK3WWZCwInfpCG5BMpKagcchJDi.jpg',
                'created_at' => '2024-07-17 21:09:01',
                'updated_at' => '2024-07-17 21:09:01',
            ],
            [
                'id' => 5,
                'title' => 'トイ・ストーリー', //id=5
                'tmdb_id' => 862,
                'original_title' => 'Toy Story',
                'overview' => 'カウボーイ人形のウッディはアンディ少年の大のお気に入り。だがそれも誕生日プレゼントでアクション人形バズ・ライトイヤーを手にするまでの事だ った。NO．1の座を奪われたウッディは何とかバズをこらしめようとするが、バズはバズで自分が本物のスペース・レンジャーだと思い込んでいる有り様。そんな二人がふと したいざこざから外の世界に飛び出してしまう。なんとか我が家へ帰還しようとする二人だが、なんとアンディの隣に住む悪ガキのシドに捕まってしまった……。',
                'release_year' => 1995,
                'director' => 'ジョン・ラセター',
                'country_id' => 2,
                'image1' => '/lxD5ak7BOoinRNehOCA85CQ8ubr.jpg',
                'image2' => '/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg',
                'created_at' => '2024-07-17 21:09:01',
                'updated_at' => '2024-07-17 21:09:01',
            ],
            [
                'id' => 6,
                'title' => '地底怪物',
                'tmdb_id' => 943344,
                'original_title' => '地底怪物',
                'overview' => '',
                'release_year' => 2023,
                'director' => 'Wei Wei',
                'image1' => '/oSJV6nAfHzyE9v6oEAXmDjbko00.jpg',
                'image2' => '/1vwX9SdsibTUnO4LAknQaqBV6aL.jpg',
                'country_id' => 12,
                'created_at' => '2024-07-18 21:09:01',
                'updated_at' => '2024-07-18 21:09:01',
            ],
            [
                'id' => 7,
                'title' => '宇宙＋人 1部',
                'tmdb_id' => 601796,
                'original_title' => '외계+인 1부',
                'overview' => '',
                'release_year' => 2022,
                'director' => '류준열',
                'image1' => '/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg',
                'image2' => '/ymkbn5pkj5wGcNr5IoKMdBtB55V.jpg',
                'country_id' => 11,
                'created_at' => '2024-07-18 21:09:07',
                'updated_at' => '2024-07-18 21:09:07',
            ],
            [
                'id' => 8,
                'title' => 'スパイダーマン：ノー・ウェイ・ホーム',
                'tmdb_id' => 634649,
                'original_title' => 'Spider-Man: No Way Home',
                'overview' => '倒した敵の暴露により、世間から悪評を受けるスパイダーマン。自分の正体が知られていない世界に戻りたいと思うようになった彼は、友人のドクター・ストレンジに助けを求める。やがて魔法の力で、彼は違う世界線で2つの人生を同時に歩み始める',
                'release_year' => 2021,
                'director' => 'Tom Holland',
                'image1' => '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
                'image2' => '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:09:12',
                'updated_at' => '2024-07-18 21:09:12',
            ],
            [
                'id' => 9,
                'title' => 'バッドボーイズ フォー・ライフ',
                'tmdb_id' => 38700,
                'original_title' => 'Bad Boys for Life',
                'overview' => 'リッチでプレイボーイな敏腕刑事マイク・ローリーと、彼の相棒で家族想いな刑事マーカス・バーネット。数々の共同捜査を乗り越え、“バッドボーイズ”として活躍する2人だったが、マーカスが危険な職務からの引退を決意。一人になったマイクは上司からの指令を受け、若手エリートたちとチームを組むことになる。新チームで事件の捜査に臨むマイクだったが、彼に因縁を持つ何者かによって命をねらわれる・・・。',
                'release_year' => 2020,
                'director' => 'ウィル・スミス',
                'image1' => '/eAIHqfS3kXm7kZl4j7ZBfdegyEz.jpg',
                'image2' => '/3N316jUSdhvPyYTW29G4v9ebbcS.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:09:16',
                'updated_at' => '2024-07-18 21:09:16',
            ],
            [
                'id' => 10,
                'title' => 'ディセンダント3',
                'tmdb_id' => 506574,
                'original_title' => 'Descendants 3',
                'overview' => '平和だった王国に最大の危機が迫る！ ディズニーの世界的大ヒット ミュージカル、ついに完結！ “善”と“悪”を現代の視点で描き、世界的大ヒットを記録した「ディセンダント」の3作目。マル、イヴィ、カルロス、ジェイはオラドン王国に招くヴィランズの子ども達を選抜するため再びロスト島を訪れる。ところが、島を覆っていたバリアが開いている間にヴィランが攻撃を仕掛ける事件が…。ウーマとハデスがオラドン王国に復讐することを恐れたマルは、バリアを閉ざし、自分の故郷・ロスト島を永遠に封印する決断をするが、得体の知れない闇が忍び寄っていた。',
                'release_year' => 2019,
                'director' => 'Dove Cameron',
                'image1' => '/p0boFm5Z1HzO6LHMBuLYUM48iVV.jpg',
                'image2' => '/edR425u4p7heawbO3g6imVEEKEc.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:09:19',
                'updated_at' => '2024-07-18 21:09:19',
            ],
            [
                'id' => 11,
                'title' => 'アベンジャーズ／インフィニティ・ウォー',
                'tmdb_id' => 299536,
                'original_title' => 'Avengers: Infinity War',
                'overview' => '宇宙において最凶・最悪の存在であるサノスが、自身の野望の実現に向けて立ち上がる。それは宇宙で生きている者の半分を葬り去り、“バランスの取れた宇宙”を実現するというもの。サノスはそのために、6つそろえればその野望を叶えることができる“インフィニティ・ストーン”を集め始める。サノスはまず、ソーとハルクが乗ったアスガルドの宇宙船を襲い、やがてドクター・ストレンジらがいる地球のニューヨークにも襲い掛かる。',
                'release_year' => 2018,
                'director' => 'ロバート・ダウニー・Jr',
                'image1' => '/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
                'image2' => '/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:09:24',
                'updated_at' => '2024-07-18 21:09:24',
            ],
            [
                'id' => 12,
                'title' => 'ブレードランナー 2049',
                'tmdb_id' => 335984,
                'original_title' => 'Blade Runner 2049',
                'overview' => '2022年にアメリカ西海岸で大規模な停電が起きたのをきっかけに世界は食物供給が混乱するなど危機的状況を迎える。2025年、科学者ウォレスが遺伝子組み換え食品を開発し、人類の危機を救う。そして、元捜査官デッカードが突然行方をくらませて以来30年の月日が流れた2049年には、レプリカント（人造人間）の寿命に制限がなくなっていた。',
                'release_year' => 2017,
                'director' => 'ライアン・ゴズリング',
                'image1' => '/ilRyazdMJwN05exqhwK4tMKBYZs.jpg',
                'image2' => '/m7ynwXIvSnhxQPR6pOICrC0L2sO.jpg',
                'country_id' => 8,
                'created_at' => '2024-07-18 21:09:34',
                'updated_at' => '2024-07-18 21:09:34',
            ],
            [
                'id' => 13,
                'title' => 'ジェーン・ドウの解剖',
                'tmdb_id' => 397243,
                'original_title' => 'The Autopsy of Jane Doe',
                'overview' => '遺体安置所を舞台に身元不明女性遺体の検死から、さまざまな怪現象が巻き起こる恐怖を、リアルな解剖シーンの描写を交えて描いたホラー作品。バージニア州の田舎町で息子のオースティンとともに遺体安置所と火葬場を経営するベテラン検死官トミー。ある夜、保安官から入った緊急の検死依頼は、一家3人が惨殺された家屋の地下から裸で発見された身元不明女性、通称「ジェーン・ドウ」の検死だった。解剖を進めていく中で、遺体に隠されたある事実が判明し、閉ざされた遺体安置所にさまざまな怪奇現象が発生する。',
                'release_year' => 2016,
                'director' => 'Emile Hirsch',
                'image1' => '/7GEi50BH2gjWuhoAx55Mmb0f7Vj.jpg',
                'image2' => '/t1HoWfpmYmWc4nJ1vY38545qncP.jpg',
                'country_id' => 3,
                'created_at' => '2024-07-18 21:09:36',
                'updated_at' => '2024-07-18 21:09:36',
            ],
            [
                'id' => 14,
                'title' => 'インサイド・ヘッド',
                'tmdb_id' => 150540,
                'original_title' => 'Inside Out',
                'overview' => '田舎町に暮らす11歳の女の子ライリーは、父親の仕事の影響で都会のサンフランシスコに移り住むことになる。新しい生活に慣れようとするライリーの頭の中では、ヨロコビ、カナシミ、イカリ、ビビリ、ムカムカたちが、ライリーの幸せのためという強い気持ちが原因で衝突していて……。〈11歳の少女の頭の中を舞台に、喜び、怒り、嫌悪、恐れ、悲しみといった感情がそれぞれキャラクターとなり、物語を繰り広げるディズニー/ピクサーによるアニメ。田舎から都会への引っ越しで環境が変化した少女の頭の中で起こる、感情を表すキャラクターたちの混乱やぶつかり合いなどを描く。メガホンを取るのは、『モンスターズ・インク』や『カールじいさんの空飛ぶ家』などの監督ピート・ドクター。〉',
                'release_year' => 2015,
                'director' => 'エイミー・ポーラー',
                'image1' => '/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg',
                'image2' => '/o3i6AfTcWAuNvzAUV3q5lOmi6Gx.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:09:40',
                'updated_at' => '2024-07-18 21:09:40',
            ],
            [
                'id' => 15,
                'title' => '猿の惑星：新世紀（ライジング）',
                'tmdb_id' => 119450,
                'original_title' => 'Dawn of the Planet of the Apes',
                'overview' => 'カリスマ的な統率力を誇る猿のシーザーが、仲間を率いて人類への反乱を起こしてから10年後。遺伝子の進化、知能と言語の獲得により猿たちはさらに進化を遂げ、独自の文明を形成、森の奥に平和なコミュニティを築いていた。一方、10年前に自らが生み出したウイルスにより人類は90％が死に追いやられ、僅かな生存者グループは、荒廃した都市部の一角に身を潜め、希望なき日々を過ごしている。そんなある日、人間たちが資源を求めて森に足を踏み入れたことから、猿たちとの間に危うい緊張が走る。',
                'release_year' => 2014,
                'director' => 'Andy Serkis',
                'image1' => '/4TFCA5Lm5miseV3Wy02yxurEQL9.jpg',
                'image2' => '/mYT8Epw2JJIKKbWdwZDlw4hmSbK.jpg',
                'country_id' => 3,
                'created_at' => '2024-07-18 21:09:46',
                'updated_at' => '2024-07-18 21:09:46',
            ],
            [
                'id' => 16,
                'title' => '怪盗グルーのミニオン危機一発',
                'tmdb_id' => 93456,
                'original_title' => 'Despicable Me 2',
                'overview' => '皮肉屋の怪盗グルーは心を入れ替え、バナナが大好きなミニオンたちに支えられながらマイホームパパになろうと努力していた。ある日、彼は世界トップクラスの超極秘組織「反悪党同盟」に引き抜かれ、相棒のルーシーと共に捜査にあたることになる。そんな折り、彼の家から無敵のチームであるミニオンたちが何者かにさらわれてしまう。',
                'release_year' => 2013,
                'director' => 'スティーヴ・カレル',
                'image1' => '/fOipappvgVtUbbHOtmCkHzcwJjC.jpg',
                'image2' => '/1djFa00NGyqTFYvZCw8M1a2Y1Lw.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:09:48',
                'updated_at' => '2024-07-18 21:09:48',
            ],
            [
                'id' => 17,
                'title' => 'クライモリ デッド・パーティ',
                'tmdb_id' => 125509,
                'original_title' => 'Wrong Turn 5: Bloodlines',
                'overview' => '',
                'release_year' => 2012,
                'director' => 'Camilla Arfwedson',
                'image1' => '/1dFKtwFarEj47JRJHe9dPpMLyQF.jpg',
                'image2' => '/99frHbFBOgjD9ffjxDTf5B5xhuh.jpg',
                'country_id' => 7,
                'created_at' => '2024-07-18 21:09:59',
                'updated_at' => '2024-07-18 21:09:59',
            ],
            [
                'id' => 18,
                'title' => 'TIME／タイム',
                'tmdb_id' => 49530,
                'original_title' => 'In Time',
                'overview' => '科学の進化により老化を克服した近未来、そこでは‘時間’が‘通貨’となり世界を支配していた。人間の成長は25歳で止まり、余命（時間）は労働により稼がなければならなかった。そして街は‘タイムゾーン’という境界線により、貧困層が住む〈スラム・ゾーン〉と〈富裕ゾーン〉に明確に分けられ、その行き来は禁止されていた。ある日、ある男から100年の時間をもらったことで殺人容疑をかけられた貧困層の青年ウィルは、スラムゾーンに別れを告げ、富裕ゾーンに逃げ込む。',
                'release_year' => 2011,
                'director' => 'Justin Timberlake',
                'image1' => '/kx2YVkcsnTnmF9XGTAj2NqEcHFG.jpg',
                'image2' => '/q0W5elJSBywFhkuRHCbPfRegP45.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:06',
                'updated_at' => '2024-07-18 21:10:06',
            ],
            [
                'id' => 19,
                'title' => 'アイアンマン2',
                'tmdb_id' => 10138,
                'original_title' => 'Iron Man 2',
                'overview' => 'パワード・スーツ受け渡しの国家命令を拒否した科学者兼経営者のトニー・スターク。ある日、トニーの前にウィップラッシュなるアイアンマンと互角のパワーを持つ敵が現れたことから、トニーは再びパワード・スーツに身を包みアイアンマンとして立ち上がる。',
                'release_year' => 2010,
                'director' => 'ロバート・ダウニー・Jr',
                'image1' => '/7lmBufEG7P7Y1HClYK3gCxYrkgS.jpg',
                'image2' => '/r7ZrIpRSiQGAzYZCLvmuDgbRRqB.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:09',
                'updated_at' => '2024-07-18 21:10:09',
            ],
            [
                'id' => 20,
                'title' => 'コララインとボタンの魔女',
                'tmdb_id' => 14836,
                'original_title' => 'Coraline',
                'overview' => 'ピンクパレスアパートに引っ越してきた少女コラライン。しかし、両親は多忙な仕事で、構ってもらえず、友人も出来ない退屈で孤独な日々を送っていた。そんなある日コララインは、壁に封印された小さなドアを見つけた。ドアを開けて中に入ると、そこは目がボタンの"別の両親"が住むどんな願いも叶う夢の世界だった。コララインは、この世界をすっかり気に入るが、この世界で暮らすには、目をボタンにしなければならないのだった。',
                'release_year' => 2009,
                'director' => 'ダコタ・ファニング',
                'image1' => '/8GHxjXlI5rqyTBuVNekGTPjG5T6.jpg',
                'image2' => '/p5ixxu4V6VYBvr26xBKsaPrElu6.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:12',
                'updated_at' => '2024-07-18 21:10:12',
            ],
            [
                'id' => 21,
                'title' => 'トワイライト〜初恋〜',
                'tmdb_id' => 8966,
                'original_title' => 'Twilight',
                'overview' => '今どきの女子高生とは違う、内気で風変わりなベラ。母親の再婚を機に父と暮らすことにしたベラは、転入先で美少年のエドワードと出会う。知的で謎めいたエドワードに惹かれていくベラだったが、彼は1918年から年を取っていない不死のバンパイアだった。',
                'release_year' => 2008,
                'director' => 'クリステン・スチュワート',
                'image1' => '/7eK8FJr4fqq3J5W2xvlr2GVaep2.jpg',
                'image2' => '/20pEc3LeWSs5MCtVwTMPxpZqDE6.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:16',
                'updated_at' => '2024-07-18 21:10:16',
            ],
            [
                'id' => 22,
                'title' => 'デッド・サイレンス',
                'tmdb_id' => 14001,
                'original_title' => 'Dead Silence',
                'overview' => '',
                'release_year' => 2007,
                'director' => 'Ryan Kwanten',
                'image1' => '/xMjAkXpCb55FTAV7By31p3TQMxb.jpg',
                'image2' => '/l6n41u1qnCJE9J9qzgkD0GRN2eB.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:21',
                'updated_at' => '2024-07-18 21:10:21',
            ],
            [
                'id' => 23,
                'title' => 'プラダを着た悪魔',
                'tmdb_id' => 350,
                'original_title' => 'The Devil Wears Prada',
                'overview' => '恋に仕事にがんばるあなたへ贈る、ゴージャス＆ユーモラスなサクセスストーリー。大学を卒業し、ジャーナリストをめざしてNYにやってきたアンディ。オシャレに興味のない彼女が、一流ファッション誌‘RUNWAY’のカリスマ編集長ミランダ・プリーストリーのアシスタントに。そこは恐怖のポストだった！キャリアのためとはいえ、私生活はめちゃめちゃ。私って、本当は何をしたいんだっけ？',
                'release_year' => 2006,
                'director' => 'メリル・ストリープ',
                'image1' => '/CpLAfXgSNeNRRbRzPrTuzKmIHO.jpg',
                'image2' => '/vJUkmeOfMxeyobEtbhCRSJ30sv.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:24',
                'updated_at' => '2024-07-18 21:10:24',
            ],
            [
                'id' => 24,
                'title' => 'ナルニア国物語／第1章：ライオンと魔女',
                'tmdb_id' => 411,
                'original_title' => 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
                'overview' => '第二次世界大戦下のイギリス。ペベンシー家の4人の兄妹-ピーター、スーザン、エドマンド、ルーシーは、ロンドンの空襲を逃れて田舎に住むカーク教授に預けられる。古めかしく広大な教授の屋敷は、子供たちにとって最高の探検場所。好奇心旺盛な末っ子のルーシーは、“かくれんぼ”をしているうちに、空き部屋で大きな古い衣装だんすをみつける。見えない力に導かれるかのように衣装だんすに入り、毛皮のコートを押しのけて奥に進むといつしかルーシーは雪に覆われた真夜中の森に立っていた。',
                'release_year' => 2005,
                'director' => 'Georgie Henley',
                'image1' => '/9iRRfMZbnpgHDdKi2lczGGYZXDo.jpg',
                'image2' => '/uzFcA1qOhWPyBL5fUXHIxi26Miw.jpg',
                'country_id' => 3,
                'created_at' => '2024-07-18 21:10:29',
                'updated_at' => '2024-07-18 21:10:29',
            ],
            [
                'id' => 25,
                'title' => 'ハウルの動く城',
                'tmdb_id' => 4935,
                'original_title' => 'ハウルの動く城',
                'overview' => '父親の帽子店で帽子を作って暮らしていた18歳のソフィーは、荒野の魔女の呪いで90歳の老婆の姿になってしまう。彼女はハンサムだが気弱な魔法使いハウルと出会って、彼の居城でいっしょに暮らすようになるが、その城は4本足で歩く動く城だった。',
                'release_year' => 2004,
                'director' => 'Chieko Baisho',
                'image1' => '/pjy0T63vIFYvxRSJ3ZtjB4tmWV4.jpg',
                'image2' => '/nv5wwZou159v5OC61i4ElR7OqyY.jpg',
                'country_id' => 1,
                'created_at' => '2024-07-18 21:10:32',
                'updated_at' => '2024-07-18 21:10:32',
            ],
            [
                'id' => 26,
                'title' => 'パイレーツ・オブ・カリビアン／呪われた海賊たち',
                'tmdb_id' => 22,
                'original_title' => 'Pirates of the Caribbean: The Curse of the Black Pearl',
                'overview' => '17世紀、海賊たちが大海原を荒らしまわっていた遥かなる時代。カリブ海の港町ポートロイヤル。美しい総督の娘エリザベスはかつて海上で助けた少年ウィルが身につけていた黄金のメダルを手に入れ、今も密かに保管していた。そんなある日、突然ブラックパール号に乗ったキャプテン・バルボッサ率いる冷酷な海賊たちが町に現われ、エリザベスがさらわれてしまう。海賊の目的は、彼女がその時身につけていた例のメダルだった。一方、鍛冶屋で働く逞しい若者へと成長したウィルは、幽閉されていた元ブラックパール号船長で一匹狼の海賊ジャック・スパロウと手を組み、エリザベスの救出に向かうのだが…。',
                'release_year' => 2003,
                'director' => 'ジョニー・デップ',
                'image1' => '/wW7Wt5bXzPy4VOEE4LTIUDyDgBo.jpg',
                'image2' => '/7yxjg8pvp3JuqguUaJPYTma6Z7t.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:36',
                'updated_at' => '2024-07-18 21:10:36',
            ],
            [
                'id' => 27,
                'title' => 'トリプルX',
                'tmdb_id' => 7451,
                'original_title' => 'xXx',
                'overview' => 'ザンダーは命を懸けたスポーツ“Xゲーム”で若者たちにその名を知られるカリスマ的な存在。どんな危険なゲームも平然とやってのけるその驚異的な身体能力と冷静な判断力が、やがて国家安全保障局（NSA）の目に留まる。NSAのベテラン・エージェント、ギボンズは強引にザンダーを説き伏せ、彼をシークレット・エージェントに任命する。任務とは、既に3人のエージェントが見破られ抹殺されていた過激な犯罪集団“アナーキー99”への潜入捜査だった。',
                'release_year' => 2002,
                'director' => 'ヴィン・ディーゼル',
                'image1' => '/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg',
                'image2' => '/alops4VVk7U4PKjexiHKAKigR4f.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:40',
                'updated_at' => '2024-07-18 21:10:40',
            ],
            [
                'id' => 28,
                'title' => 'グラディエーター',
                'tmdb_id' => 98,
                'original_title' => 'Gladiator',
                'overview' => 'リドリー・スコット監督が放つスペクタクル活劇。古代ローマ帝国を舞台に、陰謀に陥れられた英雄騎士の死闘をダイナミックに描く。西暦180年、皇帝に絶大な信頼を置かれていた歴戦の勇者マキシマスは、次期皇帝の任を依頼される。しかしその晩、皇帝は息子によって暗殺。罠にはまったマキシマスは、処刑の危機に陥る。',
                'release_year' => 2000,
                'director' => 'ラッセル・クロウ',
                'image1' => '/hND7xAaxxBgaIspp9iMsaEXOSTz.jpg',
                'image2' => '/1g2Oribnq9fLTBqLQtLIhA7X1Zy.jpg',
                'country_id' => 3,
                'created_at' => '2024-07-18 21:10:48',
                'updated_at' => '2024-07-18 21:10:48',
            ],
            [
                'id' => 29,
                'title' => 'トイ・ストーリー2',
                'tmdb_id' => 863,
                'original_title' => 'Toy Story 2',
                'overview' => 'ある日、ウッディがオモチャ屋のアルにさらわれてしまう。ビンテージ品としての価値に目を付けたアルは、彼を博物館へ売りつけようと奔走。ウッディの友人であるバズたちは、彼を助けるためアルの行方を追う。',
                'release_year' => 1999,
                'director' => 'トム・ハンクス',
                'image1' => '/1dvOCqKgBcXvfqzVPmAAM5Rv4PP.jpg',
                'image2' => '/tPK1kSevALeVGPfDFv1pwyHnoJ9.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:57',
                'updated_at' => '2024-07-18 21:10:57',
            ],
            [
                'id' => 30,
                'title' => 'ムーラン',
                'tmdb_id' => 10674,
                'original_title' => 'Mulan',
                'overview' => 'フン族の軍勢に苦しむ戦乱の中国。皇帝は各家から一人の兵士を出すように命じる。ムーランは、老いた父親に代わって軍に兵士として加わることを決意。髪を切り名前をビンと変え、勇猛な兵士に変装する。ムーランは過酷な訓練を経て、戦場で目をみはる大活躍を繰り広げる。',
                'release_year' => 1998,
                'director' => 'Ming-Na Wen',
                'image1' => '/mUYV0ZdsDEliGaQahcQH1F3grsP.jpg',
                'image2' => '/sbz1e9a7mDu4Mr2gChlohiYzfqu.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:10:59',
                'updated_at' => '2024-07-18 21:10:59',
            ],
            [
                'id' => 31,
                'title' => 'タイタニック',
                'tmdb_id' => 597,
                'original_title' => 'Titanic',
                'overview' => '1912年、処女航海に出た豪華客船タイタニック号。新天地アメリカを目指す画家志望の青年ジャックと上流階級の娘ローズは船上で運命的な出会いを果たす。身分違いの恋を乗り越え強い絆で結ばれていく2人。しかし不沈を誇っていた豪華客船は皮肉な運命に見舞われる‥‥。',
                'release_year' => 1997,
                'director' => 'Leonardo DiCaprio',
                'image1' => '/sDH1LkdFOkQmTJaF1sIIniQyFOk.jpg',
                'image2' => '/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:03',
                'updated_at' => '2024-07-18 21:11:03',
            ],
            [
                'id' => 32,
                'title' => 'ツイスター',
                'tmdb_id' => 664,
                'original_title' => 'Twister',
                'overview' => 'スピルバーグ製作総指揮、M・クライトン脚本に加え、「スピード」でメガヒットを飛ばしたJ・デ・ボンがメガホンを取ったパニック・スペクタクル。竜巻内に調査用のセンサーを送り込む事で早期警報の実現を図ろうとする研究者グループと、それに対抗するグループとの競走を、迫力のCGを駆使した竜巻の映像で描く。',
                'release_year' => 1996,
                'director' => 'Helen Hunt',
                'image1' => '/oxwmEydtZm7Gk4fSHxxVieM3KnH.jpg',
                'image2' => '/vqvNIR4CjcBIh5VhKF9ThhK67hw.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:07',
                'updated_at' => '2024-07-18 21:11:07',
            ],
            [
                'id' => 33,
                'title' => 'セブン',
                'tmdb_id' => 807,
                'original_title' => 'Se7en',
            'overview' => '定年退職間近の刑事サマセットと新人のミルズは、ある殺人現場に向かう。そこには肥満の大男の凄惨な死体があった。またほどなくして、今度はビジネスマンの死体が発見される。サマセットはそれぞれの現場に残されていた文字から、犯人がキリスト教における七つの大罪(傲慢・嫉妬・憤怒・怠惰・強欲・暴食・色欲)に因んだ殺人に及んでいると分析、残るは5件となった。事件を未然に防ごうと犯人の特定を急ぐ2人。やがて一人の男が容疑者に浮上、しかし接近するも取り逃がし、さらなる犠牲者を出してしまう。そんな中、大罪に沿った犯行が残り2件となったところで、犯人を名乗る男が自首して来るのだが…。',
                'release_year' => 1995,
                'director' => 'モーガン・フリーマン',
                'image1' => '/dYjZ27hDw2QFaEIfzbNGwW0IkV9.jpg',
                'image2' => '/xfAi4XOuXSLhQXM7lsgEwO3X17H.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:10',
                'updated_at' => '2024-07-18 21:11:10',
            ],
            [
                'id' => 34,
                'title' => 'レオン',
                'tmdb_id' => 101,
                'original_title' => 'Léon: The Professional',
                'overview' => 'リュック・ベッソンが初めてアメリカで製作したバイオレンス・アクション。ニューヨークを舞台に、凄腕の殺し屋レオンと12歳の少女マチルダの純愛と戦いを描く。大都会の片隅で出会った孤独なふたりの葛藤と壮絶なアクション・シーンがほどよくブレンドされた佳作。',
                'release_year' => 1994,
                'director' => 'Jean Reno',
                'image1' => '/jynfI114q3kOAbIiVjVfFFmttU2.jpg',
                'image2' => '/oh6lykRqUG0FEUQW2Bci92MM9rI.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:14',
                'updated_at' => '2024-07-18 21:11:14',
            ],
            [
                'id' => 35,
                'title' => 'エマニエル パリの熱い夜',
                'tmdb_id' => 253935,
                'original_title' => 'Emmanuelle au 7ème ciel',
                'overview' => '',
                'release_year' => 1993,
                'director' => 'Sylvia Kristel',
                'image1' => '/mrspEgfpOFtGcX7f2mXUOQo10Dl.jpg',
                'image2' => NULL,
                'country_id' => 6,
                'created_at' => '2024-07-18 21:11:17',
                'updated_at' => '2024-07-18 21:11:17',
            ],
            [
                'id' => 36,
                'title' => '杏林春暖',
                'tmdb_id' => 1107028,
                'original_title' => '杏林春暖',
                'overview' => '',
                'release_year' => 1992,
                'director' => 'Yuet-Sin Lee',
                'image1' => '/4jG62l8qpkStFxifXo1Irv8HzV9.jpg',
                'image2' => '/9aCCcUvCelnbR43f8wxUorfknFa.jpg',
                'country_id' => 15,
                'created_at' => '2024-07-18 21:11:20',
                'updated_at' => '2024-07-18 21:11:20',
            ],
            [
                'id' => 37,
                'title' => 'La Riffa',
                'tmdb_id' => 59053,
                'original_title' => 'La Riffa',
                'overview' => '',
                'release_year' => 1991,
                'director' => 'モニカ・ベルッチ',
                'image1' => '/xGhwfRxTsP9VhDSNsfHqBcRvWKY.jpg',
                'image2' => '/zcMFc2dTQOjQHtXEarNNrQFuWrn.jpg',
                'country_id' => 4,
                'created_at' => '2024-07-18 21:11:23',
                'updated_at' => '2024-07-18 21:11:23',
            ],
            [
                'id' => 38,
                'title' => 'ゴッドファーザー PART III',
                'tmdb_id' => 242,
                'original_title' => 'The Godfather Part III',
                'overview' => 'コルレオーネ・ファミリーを描いた壮大なドラマの最終章。ファミリーのドンとなったマイケルは、バチカンの加護を得て一切の犯罪から手を引くことを宣言した。だが後継者に甥のビンセントを立てたことから内部抗争に火がついてしまう。自身も病に蝕まれるマイケルは何とか事態の収拾を図ろうとするのだが……。',
                'release_year' => 1990,
                'director' => 'Al Pacino',
                'image1' => '/zNnjHLDtV8Ti3aworltaeaLMov4.jpg',
                'image2' => '/sEp4vZOXFZCf1GfVL0CabcMHOnY.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:28',
                'updated_at' => '2024-07-18 21:11:28',
            ],
            [
                'id' => 39,
                'title' => 'リトル・マーメイド',
                'tmdb_id' => 10144,
                'original_title' => 'The Little Mermaid',
                'overview' => 'トリトン王が治める海の王国。16歳になる王の末娘アリエルは、見たことのない人間の世界に憧れていた。ある嵐の日、船から海に落ちた人間の王子エリックを助けたアリエルは、ハンサムな彼に恋してしまう。彼を忘れられないアリエルは、魔女アースラに頼み、自分の声と引き替えに人間になれる魔法をかけてもらった。だが、魔法の期限は3日間。それまでに王子と相思相愛になれなければ、彼女の魂は魔女に奪われてしまうのだ。',
                'release_year' => 1989,
                'director' => 'ジョディ・ベンソン',
                'image1' => '/wQle1uFv6qKWvv0dk8r5oe6mMP4.jpg',
                'image2' => '/eP7nUQ5pYLi3prJfM4YWWBXfY4U.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:37',
                'updated_at' => '2024-07-18 21:11:37',
            ],
            [
                'id' => 40,
                'title' => '肉体の門',
                'tmdb_id' => 383634,
                'original_title' => '肉体の門',
                'overview' => '昭和22年、いまだ戦争の傷痕が至るところに残り、一面焼け野原が広がる東京。新橋駅界隈では、通称“関東小政”こと浅田せんや、“ボルネオマヤ”こと菅マヤら、家や家族を失って売春婦となった女性たちが徒党を組み、“らくちょうのお澄”率いるライバルグループや、闇市を仕切るヤクザの袴田一家と、縄張り争いを繰り広げていた。そんなある日、せんたちのもとに、元陸軍上等兵の伊吹新太郎がMPに追われて逃げ込んでくる。',
                'release_year' => 1988,
                'director' => 'かたせ梨乃',
                'image1' => '/lP0G6f00CjOKdRECyGrT0kaMSrL.jpg',
                'image2' => NULL,
                'country_id' => 1,
                'created_at' => '2024-07-18 21:11:40',
                'updated_at' => '2024-07-18 21:11:40',
            ],
            [
                'id' => 41,
                'title' => 'ニア・ダーク/月夜の出来事',
                'tmdb_id' => 11879,
                'original_title' => 'Near Dark',
            'overview' => '田舎町の農場で暮らすカウボーイの青年ケイレブ(エイドリアン・パスダー)は、ある月夜の晩、道端で佇むメイと名乗る美しい少女(ジェニー・ライト)と出会う。彼女の怪しげな魅力に虜となるケイレブだったが、実はメイは吸血鬼だった。メイに首筋を噛まれたことで吸血鬼へと変貌してしまったケイレブは、正体不明の一団に拉致され止む無くメイたち吸血鬼の首領ジェシー(ランス・ヘンリクセン)率いる一味に加わるのだが...。',
                'release_year' => 1987,
                'director' => 'Adrian Pasdar',
                'image1' => '/dRybvMAs3YhyqjjgGyPNuIuW4if.jpg',
                'image2' => '/eoMZh4k1vSf0ml5D9wnxRsf8SE1.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:43',
                'updated_at' => '2024-07-18 21:11:43',
            ],
            [
                'id' => 42,
                'title' => 'トップガン',
                'tmdb_id' => 744,
                'original_title' => 'Top Gun',
                'overview' => 'カリフォルニア州ミラマー海軍航空基地。そこにF－14トムキャットを操る世界最高のパイロットたちを養成する訓練学校、通称“トップガン”がある。若きパイロットのマーヴェリックもパートナーのグースとともにこのトップガン入りを果たし、自信と野望を膨らませる。日々繰り返される厳しい訓練も、マーヴェリックはグースとの絶妙なコンビネーションで次々と課題をクリアしていく。しかしライバルのアイスマンは、彼の型破りな操縦を無謀と指摘する。その一方で、マーヴェリックは新任の女性教官チャーリーに心奪われていく。',
                'release_year' => 1986,
                'director' => 'トム・クルーズ',
                'image1' => '/j6sAlNz354qtzvG01LLYF16Uufg.jpg',
                'image2' => '/yyw9qZfJndOjXXe5t8bwyw4mXIN.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:48',
                'updated_at' => '2024-07-18 21:11:48',
            ],
            [
                'id' => 43,
                'title' => 'バック・トゥ・ザ・フューチャー',
                'tmdb_id' => 105,
                'original_title' => 'Back to the Future',
                'overview' => 'スティーブン・スピルバーグとロバート・ゼメキスが贈るSFアドベンチャーシリーズ第1弾。高校生のマーティは、科学者・ドクの発明したタイムマシン・デロリアンで過去にタイムスリップしてしまう。',
                'release_year' => 1985,
                'director' => 'マイケル・J・フォックス',
                'image1' => '/hxSB02ksqnkXY4hPGAXqgO2fL01.jpg',
                'image2' => '/gC9OxPear9UH4gnlQ7nwF9o5us4.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:54',
                'updated_at' => '2024-07-18 21:11:54',
            ],
            [
                'id' => 44,
                'title' => 'ビバリーヒルズ・コップ',
                'tmdb_id' => 90,
                'original_title' => 'Beverly Hills Cop',
                'overview' => '腕はいいが問題ばかり起こし、上司のトッド警部からも見放されたような状態のデトロイト市警察本部の若手刑事・アクセル（エディ・マーフィー）は、ビバリーヒルズからやってきた幼馴染のマイキーと再会するが、その夜にマイキーが殺害される。マイキーの仇討ちを決意したアクセルは、犯人を追って単独でビバリーヒルズに乗り込み、規則に忠実で洗練された地元（ビバリーヒルズ警察）の刑事達と衝突しつつも巨悪に迫る。',
                'release_year' => 1984,
                'director' => 'エディ・マーフィ',
                'image1' => '/tKi5HYDSuxP4I26fxyF2UVvAtLa.jpg',
                'image2' => '/brJaRHLNWsLNSB8AcYGqO5HyJ1A.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:11:58',
                'updated_at' => '2024-07-18 21:11:58',
            ],
            [
                'id' => 45,
                'title' => '大逆転',
                'tmdb_id' => 1621,
                'original_title' => 'Trading Places',
                'overview' => 'フィラルデフィア。一方は、大会社の経営陣のひとりとして手腕を見せるエリートで金持ち青年ルイス・ウィンソープ。もう一方は、サギまがいの事をやりながら生きている貧しい黒人青年ビリー・バレンタイン。そんな彼らの知らない所で、ウィンソープの会社の会長である2人組が、ある賭けを企んでいた。この2人の環境を入れ換えるとどうなるかという賭けである。そして、何にも知らない二人はお互いの環境が入れ替わってしまう。',
                'release_year' => 1983,
                'director' => 'Dan Aykroyd',
                'image1' => '/3FO1kbQmRlU1H6Kmn7sTfmd7mw9.jpg',
                'image2' => '/phFpSgDbgp4j6Eg0fhmueC3uyVS.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:12:01',
                'updated_at' => '2024-07-18 21:12:01',
            ],
            [
                'id' => 46,
                'title' => '13日の金曜日 PART3',
                'tmdb_id' => 9728,
                'original_title' => 'Friday the 13th Part III',
                'overview' => '',
                'release_year' => 1982,
                'director' => 'Dana Kimmell',
                'image1' => '/oGGW2bspgIuBifMwYFpSxUMijxE.jpg',
                'image2' => '/dtEkXmWPRwja6CtwPFcVpuMb7tW.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:12:05',
                'updated_at' => '2024-07-18 21:12:05',
            ],
            [
                'id' => 47,
                'title' => 'レイダース／失われたアーク《聖櫃》',
                'tmdb_id' => 85,
                'original_title' => 'Raiders of the Lost Ark',
                'overview' => '舞台は1936年。プリンストン大学で教鞭を執る高名な考古学者インディアナ・ジョーンズ教授（インディ）には、世界中の宝物を探し発見するというトレジャーハンターとしての顔があった。ある日、陸軍諜報部よりインディの下にナチス・ドイツがタニスの遺跡を発見して聖櫃（アーク）の発掘に着手したという情報が舞い込む。また情報部が傍受したドイツ軍の電報によれば、聖櫃の在り処を示す重大な手がかりラーの杖飾りはインディの恩師であるアブナー・レイヴンウッド教授の手にあるという。何としてでもナチスより先に聖櫃を手に入れろとの依頼を受け、インディは聖櫃の争奪戦に臨む。',
                'release_year' => 1981,
                'director' => 'ハリソン・フォード',
                'image1' => '/c7Mjuip0jfHLY7x8ZSEriRj45cu.jpg',
                'image2' => '/5pvzMSeyQCflp5GTGybL6PpdjGd.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:12:08',
                'updated_at' => '2024-07-18 21:12:08',
            ],
            [
                'id' => 48,
                'title' => 'シャイニング',
                'tmdb_id' => 694,
                'original_title' => 'The Shining',
                'overview' => '冬の間は豪雪で閉鎖されるホテルの管理人職を得た小説家志望のジャック・トランスは、妻のウェンディーと心霊能力のある息子ダニーとともにホテルへやってくる。そのホテルでは、かつて精神に異常をきたした管理人が家族を惨殺するという事件が起きており、当初は何も気にしていなかったジャックも、次第に邪悪な意思に飲みこまれていく。',
                'release_year' => 1980,
                'director' => 'Jack Nicholson',
                'image1' => '/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg',
                'image2' => '/AdKA2F1SzYPhSZdEbjH1Zh75UVQ.jpg',
                'country_id' => 3,
                'created_at' => '2024-07-18 21:12:13',
                'updated_at' => '2024-07-18 21:12:13',
            ],
            [
                'id' => 49,
                'title' => 'エイリアン',
                'tmdb_id' => 348,
                'original_title' => 'Alien',
                'overview' => '巨大な宇宙貨物船に侵入した一匹の異星生物の恐怖。地球への帰途についていた宇宙貨物船ノストロモ号は、謎の救難信号を受けて未知の惑星に降り立つ。そこには異星人の船があり、船内には無数の奇怪な卵が存在していた。卵から飛び出した奇妙な生物が顔に貼り付いた航宙士ケインを回収し、ノストロモ号は再び航海につくが、彼の体内にはすでに異星生物の幼体が産みつけられていたのだ。ケインの腹を突き破り姿を現したエイリアンは脱皮を繰り返し巨大に成長、一人また一人と乗組員を血祭りにあげていく……。',
                'release_year' => 1979,
                'director' => 'Tom Skerritt',
                'image1' => '/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg',
                'image2' => '/cEobq5QrnOJjO6giDs8q4RxmMKh.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:12:16',
                'updated_at' => '2024-07-18 21:12:16',
            ],
            [
                'id' => 50,
                'title' => 'ゾンビ',
                'tmdb_id' => 923,
                'original_title' => 'Dawn of the Dead',
                'overview' => '世界各地で原因が判らぬまま死体が蘇り、生きている人間を襲って食べる現象が蔓延し次第に社会は大混乱していく。アメリカ地方テレビ局のスティーブンとフランはこの状況から都市部を脱出する事にした。友人のSWAT隊員ロジャーと同僚ピーターと共にヘリコプターで人の少ない田舎を目指すが、途中孤立したショッピングモールに立ち寄る。何でもそろっているショッピングモールは隔離して中のゾンビを駆除してしまえば安全と思われ、出入り口を閉鎖し快適な空間へ作り変えていく。そんな中、暴徒と化した暴走集団がショッピングモールに目をつけ襲撃してくる。暴動集団の無計画な襲撃をやり過ごす中、ゆっくりとだが群がるゾンビが彼ら人間を確実に取り囲んでいく。',
                'release_year' => 1978,
                'director' => 'David Emge',
                'image1' => '/9OKzKuCfcMwpHVp56pjNI7J4xXR.jpg',
                'image2' => '/giTsVwG3f1bul25TVC4PvGeRoeG.jpg',
                'country_id' => 4,
                'created_at' => '2024-07-18 21:12:20',
                'updated_at' => '2024-07-18 21:12:20',
            ],
            [
                'id' => 51,
                'title' => 'スター・ウォーズ エピソード４／新たなる希望',
                'tmdb_id' => 11,
                'original_title' => 'Star Wars',
                'overview' => '遠い昔、遙か彼方の銀河では帝国軍の独裁体制が敷かれていた。反乱の機会をうかがう惑星アルデラーンのレイア姫は暗黒卿ダース・ベイダーに捕らえられるが、その寸前に二体のドロイドR2-D2とC-3POを砂漠の惑星タトゥイーンに送り込む。偶然にもそのドロイドを手に入れた青年ルークは、ジェダイの騎士団の一人オビ＝ワン・ケノービや密輸船ミレニアム・ファルコンの船長ハン・ソロたちと共に、反乱軍と帝国軍の闘いに巻き込まれていく。',
                'release_year' => 1977,
                'director' => 'Mark Hamill',
                'image1' => '/jNjT5y95BToczcxgVPl1NBB7goY.jpg',
                'image2' => '/4qCqAdHcNKeAHcK8tJ8wNJZa9cx.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:12:24',
                'updated_at' => '2024-07-18 21:12:24',
            ],
            [
                'id' => 52,
                'title' => 'La moglie di mio padre',
                'tmdb_id' => 271045,
                'original_title' => 'La moglie di mio padre',
                'overview' => '',
                'release_year' => 1976,
                'director' => 'Carroll Baker',
                'image1' => '/fjl3gXybEOg65MDIlpGXlF7iKEl.jpg',
                'image2' => NULL,
                'country_id' => 4,
                'created_at' => '2024-07-18 21:12:27',
                'updated_at' => '2024-07-18 21:12:27',
            ],
            [
                'id' => 53,
                'title' => 'ジョーズ',
                'tmdb_id' => 578,
                'original_title' => 'Jaws',
                'overview' => '米国ニュー・イングランド地方、アミティの小さな海水浴場でひとりの少女が鮫に襲われ、命を落とす事故が。警察署長のブロディは次なる犠牲者が出ぬよう、遊泳禁止を決定しようとするが、海水浴客がいなくなって町が不況に陥ることを恐れた市長の反対で失敗に。すると、今度は少年が犠牲になってしまう。ブロディは意を決して鮫を退治しようと、海洋学者フーパーや鮫狩りの専門家クイントとボートに乗り込み、海に出る。',
                'release_year' => 1975,
                'director' => 'Roy Scheider',
                'image1' => '/3nYlM34QhzdtAvWRV5bN4nLtnTc.jpg',
                'image2' => '/g6fjQh087Daxr4IOTXPxr9I4HBu.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:12:31',
                'updated_at' => '2024-07-18 21:12:31',
            ],
            [
                'id' => 54,
                'title' => 'オッペンハイマー',
                'tmdb_id' => 872585,
                'original_title' => 'Oppenheimer',
                'overview' => '第2次世界大戦中、才能にあふれた物理学者のロバート・オッペンハイマーは、核開発を急ぐ米政府のマンハッタン計画において、原爆開発プロジェクトの委員長に任命される。しかし、実験で原爆の威力を目の当たりにし、さらにはそれが実戦で投下され、恐るべき大量破壊兵器を生み出したことに衝撃を受けたオッペンハイマーは、戦後、さらなる威力をもった水素爆弾の開発に反対するようになるが……。',
                'release_year' => 2023,
                'director' => 'キリアン・マーフィー',
                'image1' => '/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg',
                'image2' => '/cUIqZd6jJCbO94Txt1CkTs7MSeP.jpg',
                'country_id' => 3,
                'created_at' => '2024-07-18 21:16:41',
                'updated_at' => '2024-07-18 21:16:41',
            ],
            [
                'id' => 55,
                'title' => 'ノリャン ―死の海―',
                'tmdb_id' => 660360,
                'original_title' => '노량: 죽음의 바다',
                'overview' => '',
                'release_year' => 2023,
                'director' => '김윤석',
                'image1' => '/ksZTspehDCC4PCZN8ci31pFT6yp.jpg',
                'image2' => '/pKTms3zLAYEPgGMvZG575l3oTw7.jpg',
                'country_id' => 11,
                'created_at' => '2024-07-18 21:16:41',
                'updated_at' => '2024-07-18 21:16:41',
            ],
            [
                'id' => 56,
                'title' => 'キングダム・オブ・ヘブン',
                'tmdb_id' => 1495,
                'original_title' => 'Kingdom of Heaven',
                'overview' => '12世紀。妻子を亡くして生きる目的を失ったフランスの鍛冶職人バリアンだが、彼の親と名乗り出たイベリンの領主、騎士ゴッドフリーに誘われ、ともにエルサレムへ出発。道中、ある事件で命を落としたゴッドフリーは騎士の称号をバリアンに譲り、エルサレムに平和と愛に満ちた国家を築くよう息子に託す。バリアンが若きエルサレム王ボードワン4世やその妹シビラ姫と出会う一方、キリスト教徒とイスラム教徒の対立は激化していく。',
                'release_year' => 2005,
                'director' => 'Orlando Bloom',
                'image1' => '/kP8rK9dGS1pr0HrnmXfIi2heWjo.jpg',
                'image2' => '/7JcYL8m1c4ZCMWU9fk7s98F6PEf.jpg',
                'country_id' => 7,
                'created_at' => '2024-07-18 21:16:42',
                'updated_at' => '2024-07-18 21:16:42',
            ],
            [
                'id' => 57,
                'title' => 'Horizon: An American Saga - Chapter 1',
                'tmdb_id' => 932086,
                'original_title' => 'Horizon: An American Saga - Chapter 1',
                'overview' => '',
                'release_year' => 2024,
                'director' => 'ケビン・コスナー',
                'image1' => '/8UOAYjhwSF3aPZhm6wgLuyHRyrR.jpg',
                'image2' => '/qwSfMUAXtqG1aLtWzhzJRZhJMmG.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:16:47',
                'updated_at' => '2024-07-18 21:16:47',
            ],
            [
                'id' => 58,
                'title' => '続・夕陽のガンマン',
                'tmdb_id' => 429,
                'original_title' => 'Il buono, il brutto, il cattivo',
                'overview' => 'コンビを組んでお尋ね者の懸賞金をだまし取っていたジョーとテュコ。二人はある日、逃走中の強奪犯から、20万ドルもの大金を奪う。だがその金をねらって、セテンサという凄腕のガンマンがやってきた……。三人の男たちの、虚虚実実の駆け引きをユーモラスに描いた痛快ウェスタン。',
                'release_year' => 1966,
                'director' => 'クリント・イーストウッド',
                'image1' => '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
                'image2' => '/3nDF7iOHUxjSV5GazK0cq1t9xUo.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:16:47',
                'updated_at' => '2024-07-18 21:16:47',
            ],
            [
                'id' => 59,
                'title' => 'The Night They Came Home',
                'tmdb_id' => 1216299,
                'original_title' => 'The Night They Came Home',
                'overview' => '',
                'release_year' => 2024,
                'director' => 'Brian Austin Green',
                'image1' => '/v8RgWCgabyym0eVOuQJaxL4GS8p.jpg',
                'image2' => '/l5qrD6Vnu80T7Mdef9Av1i04Iwf.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:16:47',
                'updated_at' => '2024-07-18 21:16:47',
            ],
            [
                'id' => 60,
                'title' => 'Destroy All Neighbors',
                'tmdb_id' => 974558,
                'original_title' => 'Destroy All Neighbors',
                'overview' => '',
                'release_year' => 2024,
                'director' => 'Jonah Ray',
                'image1' => '/zMjI3HqcpOQVcIy9poJQ6vdd2Ds.jpg',
                'image2' => NULL,
                'country_id' => 2,
                'created_at' => '2024-07-18 21:16:57',
                'updated_at' => '2024-07-18 21:16:57',
            ],
            [
                'id' => 61,
                'title' => 'ディセンダント',
                'tmdb_id' => 277217,
                'original_title' => 'Descendants',
                'overview' => 'ディセンダント＝“子孫”。そのタイトル通り、“もしディズニー・キャラクターに子孫がいて、10代だったら・・・？” という奇想天外なストーリーのディズニー・チャンネル オリジナル青春ミュージカル！',
                'release_year' => 2015,
                'director' => 'Dove Cameron',
                'image1' => '/wy3ItrIw4DmLFxvFK5LM6FPwdQw.jpg',
                'image2' => '/2wzRzSkKdKXo3t7eDif5zMSNmhJ.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:16:58',
                'updated_at' => '2024-07-18 21:16:58',
            ],
            [
                'id' => 62,
                'title' => 'ディセンダント2',
                'tmdb_id' => 417320,
                'original_title' => 'Descendants 2',
                'overview' => '晴れてベンの恋人となったマルは、正式に王室の一員となることへのプレッシャーに押しつぶされそうになり、現実逃避から、悪のルーツである生まれ故郷ロスト島へと舞い戻ってしまいます。ロスト島では、宿敵ウーマ（「リトル・マーメイド」アースラの娘）が、マルの後釜に座り、ヴィランズの子どもたちを牛耳っていた。',
                'release_year' => 2017,
                'director' => 'Dove Cameron',
                'image1' => '/fBivEVWPFI6IwCudH1BZ3YuKKuW.jpg',
                'image2' => '/7lWSgJu7q3yoeS1YQ3Ji4tGoqs5.jpg',
                'country_id' => 2,
                'created_at' => '2024-07-18 21:16:58',
                'updated_at' => '2024-07-18 21:16:58',
            ],
            [
                'id' => 63,
                'title' => 'CIVIL WAR',
                'tmdb_id' => 929590,
                'original_title' => 'Civil War',
                'overview' => '',
                'release_year' => 2024,
                'director' => 'キルスティン・ダンスト',
                'image1' => '/a4IWRYNMNMszIkRbEIiNsRg6cvt.jpg',
                'image2' => '/aFRyJ1ClU39J9IOTdlmUNa6P9A6.jpg',
                'country_id' => 15,
                'created_at' => '2024-07-18 21:17:04',
                'updated_at' => '2024-07-18 21:17:04',
            ],
            [
                'id' => 64,
                'title' => 'Battle Over Britain',
                'tmdb_id' => 1136318,
                'original_title' => 'Battle Over Britain',
                'overview' => '',
                'release_year' => 2023,
                'director' => 'Arnold Voysey',
                'image1' => '/11G6N5zW0KykVS0EcNKeXHUmQj8.jpg',
                'image2' => '/bjCts5DRvFzTrnHPE4gvvigHQSF.jpg',
                'country_id' => 3,
                'created_at' => '2024-07-18 21:17:04',
                'updated_at' => '2024-07-18 21:17:04',
            ],
            [
                'id' => 65,
                'title' => '封神第一部：朝歌风云',
                'tmdb_id' => 856289,
                'original_title' => '封神第一部：朝歌风云',
                'overview' => '',
                'release_year' => 2023,
                'director' => 'Kris Phillips',
                'image1' => '/uaSIzbRfwLidxRNMvdZAUwW3vtL.jpg',
                'image2' => '/fvaHeANnj1lkclDitqTF2gmWQTL.jpg',
                'country_id' => 12,
                'created_at' => '2024-07-18 21:17:04',
                'updated_at' => '2024-07-18 21:17:04',
            ],
        ]);
    }
}
